// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoFR1ZfYOUUXu_O7v9aPswzjFFBut2r4',
    appId: '1:105065293447:web:fcc3e3503cc7c3db887a22',
    messagingSenderId: '105065293447',
    projectId: 'cinema-55ec6',
    authDomain: 'cinema-55ec6.firebaseapp.com',
    databaseURL: 'https://cinema-55ec6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinema-55ec6.firebasestorage.app',
    measurementId: 'G-FJ79BM2CR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzPcAbEFjN7PWmznZS6Q1mO42kaeyMkpc',
    appId: '1:105065293447:web:77e32146a0e708aa887a22',
    messagingSenderId: '105065293447',
    projectId: 'cinema-55ec6',
    databaseURL: 'https://cinema-55ec6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinema-55ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYiNcdu69er35yYC8c9omi8usTg4NQuak',
    appId: '1:105065293447:ios:d05b039d8c9288fc887a22',
    messagingSenderId: '105065293447',
    projectId: 'cinema-55ec6',
    databaseURL: 'https://cinema-55ec6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinema-55ec6.firebasestorage.app',
    iosBundleId: 'com.example.cinemaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYiNcdu69er35yYC8c9omi8usTg4NQuak',
    appId: '1:105065293447:ios:d05b039d8c9288fc887a22',
    messagingSenderId: '105065293447',
    projectId: 'cinema-55ec6',
    databaseURL: 'https://cinema-55ec6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinema-55ec6.firebasestorage.app',
    iosBundleId: 'com.example.cinemaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdoFR1ZfYOUUXu_O7v9aPswzjFFBut2r4',
    appId: '1:105065293447:web:fcc3e3503cc7c3db887a22',
    messagingSenderId: '105065293447',
    projectId: 'cinema-55ec6',
    authDomain: 'cinema-55ec6.firebaseapp.com',
    databaseURL: 'https://cinema-55ec6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinema-55ec6.firebasestorage.app',
    measurementId: 'G-L94P2H5709',
  );
}
